# Generated by Django 5.1.1 on 2024-09-30 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cta/')),
                ('button_text', models.CharField(help_text='Text for the call-to-action button', max_length=50)),
                ('button_link', models.URLField(help_text='Link for the call-to-action button')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's name", max_length=100)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text="Customer's phone number (optional)", max_length=15, null=True)),
                ('message', models.TextField(help_text='Message or inquiry')),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Footer text')),
                ('phone', models.CharField(help_text='Contact number', max_length=15)),
                ('email', models.EmailField(help_text='Contact email', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTextSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sections/')),
                ('text', models.TextField(help_text='Text for the section')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=100)),
                ('description', models.TextField(help_text='Description of the product')),
                ('image', models.ImageField(help_text='Upload an image of the product', upload_to='products/')),
                ('product_type', models.CharField(choices=[('window', 'Window'), ('door', 'Door')], help_text='Specify if it is a window or door', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Stock quantity')),
                ('is_available', models.BooleanField(default=True, help_text='Product availability status')),
                ('dimensions', models.CharField(help_text='Dimensions of the product (e.g. 120x200 cm)', max_length=50)),
                ('material', models.CharField(help_text='Material used (e.g., wood, aluminum, etc.)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('caption', models.CharField(help_text='Slide caption', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Slide order')),
            ],
        ),
        migrations.CreateModel(
            name='TwoImageTwoTextSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='sections/')),
                ('text_1', models.TextField(help_text='First text block')),
                ('image_2', models.ImageField(upload_to='sections/')),
                ('text_2', models.TextField(help_text='Second text block')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=100)),
                ('email', models.EmailField(help_text='Customer email', max_length=254)),
                ('phone_number', models.CharField(help_text='Customer phone number', max_length=15)),
                ('message', models.TextField(help_text='Additional details or specific requirements')),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product for which the quote is requested', on_delete=django.db.models.deletion.CASCADE, to='windows.product')),
            ],
        ),
    ]
