# Generated by Django 5.1.1 on 2024-10-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0005_tag_order_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
