# Generated by Django 5.1.1 on 2024-10-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0008_contact_ip_address_quoterequest_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='Davis', max_length=100),
            preserve_default=False,
        ),
    ]
