# Generated by Django 5.1.1 on 2024-10-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0009_contact_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='job_type',
            field=models.CharField(choices=[('new_build', 'New Build'), ('replacements', 'Replacements'), ('extensions', 'Extensions'), ('curtain_walling', 'Curtain Walling'), ('commercial', 'Commercial'), ('not_sure', 'Not Sure')], default='New Build', max_length=50),
            preserve_default=False,
        ),
    ]
