# Generated by Django 5.1.1 on 2024-10-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0011_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
