# Generated by Django 5.1.1 on 2024-10-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0013_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('window', 'Window'), ('door', 'Door'), ('window_door_installation', 'Window Door Installation'), ('curtain_walling', 'Curtain Walling'), ('office_fit_out', 'Office Fit Out')], help_text='Specify if it is a window or door', max_length=100),
        ),
    ]
