# Generated by Django 5.1.1 on 2024-10-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0014_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us_images/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('caption', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DoorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='door_images/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WindowSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='window_images/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CallToAction',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='ImageTextSection',
        ),
        migrations.DeleteModel(
            name='Slideshow',
        ),
        migrations.DeleteModel(
            name='TwoImageTwoTextSection',
        ),
    ]
