# Generated by Django 5.1.1 on 2024-10-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0015_aboutussection_carouselimage_doorsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorsection',
            name='heading',
            field=models.CharField(default='door', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='windowsection',
            name='heading',
            field=models.CharField(default='2024', max_length=100),
            preserve_default=False,
        ),
    ]
