# Generated by Django 5.1.1 on 2024-10-10 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0016_doorsection_heading_windowsection_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Window',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='windows.product')),
                ('model_number', models.CharField(help_text='Model number of the window', max_length=50)),
                ('material_thickness', models.DecimalField(decimal_places=1, help_text='Material thickness in mm', max_digits=3)),
                ('ways_to_open', models.CharField(help_text='Ways to open the window', max_length=50)),
                ('glass_thickness', models.CharField(help_text='Glass thickness', max_length=50)),
                ('handle', models.CharField(help_text='Handle type', max_length=100)),
                ('range_opening_window_size', models.TextField(help_text='Range of opening window sizes')),
                ('energy_efficiency', models.CharField(default='Designed to minimize energy consumption', help_text='Energy efficiency feature', max_length=255)),
                ('noise_reduction', models.CharField(default='Advanced insulation technology for quieter living spaces', help_text='Noise reduction feature', max_length=255)),
                ('enhanced_security', models.CharField(default='Robust locking mechanisms for peace of mind', help_text='Security features', max_length=255)),
                ('durability_maintenance', models.CharField(default='Built to last with minimal upkeep', help_text='Durability and maintenance', max_length=255)),
                ('residential', models.BooleanField(default=True, help_text='Is this product suitable for residential use?')),
                ('commercial', models.BooleanField(default=True, help_text='Is this product suitable for commercial use?')),
                ('architectural_designs', models.BooleanField(default=True, help_text='Is this product suitable for architectural designs?')),
                ('design_integration', models.TextField(default='Our windows are designed to integrate seamlessly with your architectural vision.', help_text='Design and integration details')),
                ('professional_installation', models.BooleanField(default=True, help_text='Is professional installation recommended?')),
                ('u_value', models.DecimalField(decimal_places=2, default=0.25, help_text='Thermal performance (U-Value)', max_digits=4)),
                ('solar_heat_gain_coefficient', models.DecimalField(decimal_places=2, default=0.35, help_text='Solar Heat Gain Coefficient', max_digits=4)),
                ('sound_transmission_class', models.IntegerField(default=45, help_text='Sound insulation rating (STC)')),
                ('certifications', models.CharField(default='Energy Star, LEED Compliant', help_text='Certifications and compliances', max_length=255)),
                ('additional_image_1', models.ImageField(blank=True, help_text='First additional product image', null=True, upload_to='products/')),
                ('additional_image_2', models.ImageField(blank=True, help_text='Second additional product image', null=True, upload_to='products/')),
            ],
            bases=('windows.product',),
        ),
    ]
