# Generated by Django 5.1.1 on 2024-10-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0017_window'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='window',
            name='architectural_designs',
        ),
        migrations.RemoveField(
            model_name='window',
            name='commercial',
        ),
        migrations.RemoveField(
            model_name='window',
            name='design_integration',
        ),
        migrations.RemoveField(
            model_name='window',
            name='durability_maintenance',
        ),
        migrations.RemoveField(
            model_name='window',
            name='energy_efficiency',
        ),
        migrations.RemoveField(
            model_name='window',
            name='enhanced_security',
        ),
        migrations.RemoveField(
            model_name='window',
            name='glass_thickness',
        ),
        migrations.RemoveField(
            model_name='window',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='window',
            name='material_thickness',
        ),
        migrations.RemoveField(
            model_name='window',
            name='noise_reduction',
        ),
        migrations.RemoveField(
            model_name='window',
            name='professional_installation',
        ),
        migrations.RemoveField(
            model_name='window',
            name='range_opening_window_size',
        ),
        migrations.RemoveField(
            model_name='window',
            name='residential',
        ),
        migrations.RemoveField(
            model_name='window',
            name='ways_to_open',
        ),
        migrations.AddField(
            model_name='window',
            name='application',
            field=models.CharField(default='now', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='window',
            name='feature1',
            field=models.CharField(default='now', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='window',
            name='feature2',
            field=models.CharField(default='now', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='window',
            name='feature3',
            field=models.CharField(default='now', max_length=200),
            preserve_default=False,
        ),
    ]
