# Generated by Django 5.1.1 on 2024-10-10 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0018_remove_window_architectural_designs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorWindow',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='windows.product')),
                ('model_number', models.CharField(help_text='Model number of the window', max_length=50)),
                ('feature1', models.CharField(max_length=200)),
                ('feature2', models.CharField(max_length=200)),
                ('feature3', models.CharField(max_length=200)),
                ('application', models.CharField(max_length=200)),
                ('u_value', models.DecimalField(decimal_places=2, default=0.25, help_text='Thermal performance (U-Value)', max_digits=4)),
                ('solar_heat_gain_coefficient', models.DecimalField(decimal_places=2, default=0.35, help_text='Solar Heat Gain Coefficient', max_digits=4)),
                ('sound_transmission_class', models.IntegerField(default=45, help_text='Sound insulation rating (STC)')),
                ('certifications', models.CharField(default='Energy Star, LEED Compliant', help_text='Certifications and compliances', max_length=255)),
                ('profile_wall_thickness', models.DecimalField(decimal_places=1, default=1.8, help_text='Profile wall thickness in mm', max_digits=3)),
                ('profile_grade', models.CharField(default='6063-T5', help_text='Profile grade', max_length=10)),
                ('insulation_strip_width', models.DecimalField(decimal_places=1, default=14.8, help_text='Insulation strip width in mm', max_digits=4)),
                ('opening_method', models.CharField(default='Inward opening, inward tilting', help_text='Method of opening', max_length=100)),
                ('hardware_configuration', models.CharField(default='HOPPE, G-U', help_text='Hardware configuration', max_length=100)),
                ('opening_leaf_size_range', models.CharField(default='Width 500–1200 mm, Height 500–2800 mm', help_text='Range of opening leaf sizes', max_length=100)),
                ('glass_holding_thickness', models.CharField(default='25–54 mm', help_text='Glass holding thickness range', max_length=50)),
                ('air_tightness', models.IntegerField(default=8, help_text='Air tightness grade')),
                ('water_tightness', models.IntegerField(default=6, help_text='Water tightness grade')),
                ('wind_pressure_resistance', models.IntegerField(default=9, help_text='Wind pressure resistance grade')),
                ('sound_insulation', models.CharField(default='Up to 45 dB', help_text='Sound insulation rating', max_length=50)),
                ('burglary_resistance', models.CharField(default='Up to RC2', help_text='Burglary resistance rating', max_length=50)),
                ('regular_colors', models.CharField(default='Titanium Grey, Amber Brown, Jazz White', help_text='Regular colors', max_length=255)),
                ('optional_colors', models.CharField(blank=True, help_text='Optional colors', max_length=255)),
                ('additional_image_1', models.ImageField(blank=True, help_text='First additional product image', null=True, upload_to='products/')),
                ('additional_image_2', models.ImageField(blank=True, help_text='Second additional product image', null=True, upload_to='products/')),
            ],
            bases=('windows.product',),
        ),
        migrations.DeleteModel(
            name='Window',
        ),
    ]
