# Generated by Django 5.1.1 on 2024-10-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0019_doorwindow_delete_window'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
