# Generated by Django 5.1.1 on 2024-10-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0020_remove_product_dimensions_remove_product_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='doorwindow',
            name='solar_heat_gain_coefficient',
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='air_tightness',
            field=models.IntegerField(blank=True, default=8, help_text='Air tightness grade', null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='burglary_resistance',
            field=models.CharField(blank=True, default='Up to RC2', help_text='Burglary resistance rating', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='certifications',
            field=models.CharField(blank=True, default='Energy Star, LEED Compliant', help_text='Certifications and compliances', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='glass_holding_thickness',
            field=models.CharField(blank=True, default='25–54 mm', help_text='Glass holding thickness range', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='hardware_configuration',
            field=models.CharField(blank=True, default='HOPPE, G-U', help_text='Hardware configuration', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='insulation_strip_width',
            field=models.DecimalField(blank=True, decimal_places=1, default=14.8, help_text='Insulation strip width in mm', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='opening_leaf_size_range',
            field=models.CharField(blank=True, default='Width 500–1200 mm, Height 500–2800 mm', help_text='Range of opening leaf sizes', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='opening_method',
            field=models.CharField(blank=True, default='Inward opening, inward tilting', help_text='Method of opening', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='optional_colors',
            field=models.CharField(blank=True, help_text='Optional colors', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='profile_grade',
            field=models.CharField(blank=True, default='6063-T5', help_text='Profile grade', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='profile_wall_thickness',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.8, help_text='Profile wall thickness in mm', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='regular_colors',
            field=models.CharField(blank=True, default='Titanium Grey, Amber Brown, Jazz White', help_text='Regular colors', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='sound_insulation',
            field=models.CharField(blank=True, default='Up to 45 dB', help_text='Sound insulation rating', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='sound_transmission_class',
            field=models.IntegerField(blank=True, default=45, help_text='Sound insulation rating (STC)', null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='u_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.25, help_text='Thermal performance (U-Value)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='water_tightness',
            field=models.IntegerField(blank=True, default=6, help_text='Water tightness grade', null=True),
        ),
        migrations.AlterField(
            model_name='doorwindow',
            name='wind_pressure_resistance',
            field=models.IntegerField(blank=True, default=9, help_text='Wind pressure resistance grade', null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
