# Generated by Django 5.1.1 on 2024-10-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0021_remove_product_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='address',
            field=models.CharField(default='1 house', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='suburb',
            field=models.CharField(default='doncaster', max_length=150),
            preserve_default=False,
        ),
    ]
