# Generated by Django 5.1.1 on 2024-10-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0023_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
