# Generated by Django 5.1.1 on 2024-10-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0024_useriplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useriplog',
            name='page_visited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
