# Generated by Django 5.1.1 on 2024-10-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0026_useriplog_time_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useriplog',
            name='time_now',
            field=models.DateTimeField(),
        ),
    ]
